# Conclusion

In summary, we look into matrices related to the job market, specifically, unemployment rate and labor participation rate, through perspectives of population structure, economic factors, and educations, and try to identify characteristics that separate developed countries and developing countries. We started by defining 12,000 dollar GDP to be the cut of these two developing states. Looking into the population structure by age, we can observe that developing countries have the potential to have a growing size of available-to-work population, while developed countries are less advantageous since they have larger proportion of older people. If we separate the population by gender, one unanimity across all countries is the higher labor participation rate of male than that of female, and the gap is stunning for countries like Japan and India. Our exploration also confirms that higher level of education as well as higher literacy rate is associated with higher rate of employment across all countries. As you can probably image, the employment rate for high level of education is more steady across all years, more turbulent for lower level especially in developing countries. When we put this issue to a larger scale and look into it through the lens of world economy, we assumed that higher imports or lower exports meant negative correlation with employment for reasons like out souring. However, we observed that the labor force contribution maintains at a consistent level across years while the imports have ups and down, therefore, no obvious association. By exploring categories of import/export product, we found that high technology exports are positively correlated with labor participation rate. Based on the result, some patterns such as gender gaps are shared across all countries, but the degree of obviousness of a particular pattern could vary between countries. No particular pattern can separate developed countries from developing countries, which reassures the complexity of the issue and uniqueness of the situation faced by different countries. 
