--- 
title: "What influences employment?"
author: "Haoyu Liu, Yue Wang, James Ding "
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
Employment in a country can be affected by various factors such as development states of different countries, population structure of age groups or gender groups, and many others. A more interesting question we could ask is: do all countries in the same development state share the same features? This project will be based on the data provided by the world bank database. Based on the data provided, we will explore different variables that could have an impact on the labor market, such as imports/exports, population structures, and education. We will try to answer some questions that are related to the employment in different countries from different dimensions. We will not only compare the results between different countries and countries with the world overall but also explore the trend across time. Based on these observations, we will also be able to make some general predictions on how they will involve over time and influence the market. 

